# Operador and (y)
print(True and True)
print(True and False)
print(False and True)
print(False and False)
# Operador or (o)
print(True or False)
print(False or True)
print(False or False)
print(True or True)
# Operador not (no)
print(not True)
print(not False)
